data:
  audio_path: '../data/sample_data/vakyansh_sample'
  audio_dump_path: '../data/sample_data/'
  background_noise_path: 'background_noise/'
  background_noises: ['normalized_pink_noise.wav', 'normalized_restaurant_noise.wav', 'normalized_traffic_noise.wav']
  noise_probabilities: [0.33, 0.33, 0.33]

operations:
  volume: False
  volume_gain: [-50, -40, -30, -20, -10]
  loudness_normalization: True
  add_background_noise: False
  speed_perturb: False
  speed: 1.9